include:
  - project: 'gitlab/templates/containers'
    ref: main
    file: '/default.yml'



test-cluster:
  stage: test
  needs:
    - build
    - test
  script:
    - docker pull "${PIPELINE_IMAGE}"
    - cp -a tests "tests-${CI_COMMIT_SHORT_SHA}-${CI_CONCURRENT_ID}"
    - cd "tests-${CI_COMMIT_SHORT_SHA}-${CI_CONCURRENT_ID}"
    - sed -e "s,@@PIPELINE_IMAGE@@,${PIPELINE_IMAGE}," -e "s,@@WITH_GTID@@,," < docker-compose.yml.tmpl > docker-compose.yml
    - ./run-cluster-test


test-cluster-gtid:
  stage: test
  needs:
    - build
    - test-cluster
  script:
    - docker pull "${PIPELINE_IMAGE}"
    - cp -a tests "tests-${CI_COMMIT_SHORT_SHA}-${CI_CONCURRENT_ID}"
    - cd "tests-${CI_COMMIT_SHORT_SHA}-${CI_CONCURRENT_ID}"
    - sed -e "s,@@PIPELINE_IMAGE@@,${PIPELINE_IMAGE}," -e "s,@@WITH_GTID@@,-gtid," < docker-compose.yml.tmpl > docker-compose.yml
    - ./run-cluster-test
