#!/bin/sh


function check_tests() {
    i=120
    while [ "$i" -gt 0 ]; do
        i=$((i-1))

        echo "INFO: Waiting for tests to pass... ${i}s"

        for node in 1 2 3; do
            if docker-compose exec "node$node" test -e /PASSED; then
                echo "PASSED:   - Tests passed on node$node"
                FAILED=
            else
                FAILED=yes
            fi
        done

        if [ -z "$FAILED" ]; then
            echo "PASSED:   - PASSED ALL NODES"
            break
        fi

        sleep 1
    done

    if [ "$i" = 0 ]; then
        return 1
    fi

    return 0
}



[ -d data/node1 ] && rm -rf data/node1
[ -d data/node2 ] && rm -rf data/node2
[ -d data/node3 ] && rm -rf data/node3


mkdir -p data/node1 data/node2 data/node3

# Run in background so we can see the output
docker-compose up --remove-orphans &

# Check if our tests passed
if check_tests; then
    TESTS_PASSED=yes
fi

echo "NOTICE: Shutting down cluster"
docker-compose down --remove-orphans --volumes


if [ -z "$TESTS_PASSED" ]; then
	echo "ERROR: Cluster test failed!"
	exit 1
fi

echo "ALL TESTS PASSED!"
