#!/bin/sh
# Copyright (c) 2022-2023, AllWorldIT.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.


wait_state() {
	STATE=${1:-UKNOWN}

	i=300
	while [ "$i" -gt 0 ]; do
		i=$((i-1))

		echo "INFO: Waiting for MariaDB state $STATE... ${i}s"

		for node in 1 2 3; do
			if docker-compose exec "node$node" test -e "/${STATE}_MARIADB"; then
				echo "$STATE:   - State $STATE reached on node$node"
				FAILED=
			else
				FAILED=yes
			fi
		done

		if [ -z "$FAILED" ]; then
			echo "$STATE:   - $STATE REACHED ALL NODES"
			break
		fi

		sleep 1
	done

	if [ "$i" = 0 ]; then
		return 1
	fi

	return
}


echo "NOTICE: Starting MariaDB test replication"

# Run in background so we can see the output
docker-compose up --remove-orphans --renew-anon-volumes --force-recreate &

# Check if we're ready to start testing
if wait_state READY; then
	for node in node2 node3; do
		echo "INFO: Setting up primary on $node"
		{
			echo "CHANGE MASTER TO MASTER_HOST='node1', MASTER_USER='repluser', MASTER_PASSWORD='replpassword';"
		} | docker-compose exec -T "$node" mariadb

		echo "INFO: Initializing $node data"
		docker-compose exec -T node1 cat /root/dump.sql | docker-compose exec -T "$node" mariadb

		echo "INFO: Starting replication on $node"
		{
			echo "START SLAVE;"
		} | docker-compose exec -T "$node" mariadb
	done
fi

# Check if our tests passed
if wait_state PASSED; then
	TESTS_PASSED=yes
fi

echo "NOTICE: Shutting down MariaDB test replication"
docker-compose down --remove-orphans --volumes


if [ -z "$TESTS_PASSED" ]; then
	echo "ERROR: MariaDB replicationing tests failed!"
	exit 1
fi

echo "ALL MARIADB CLUSTER TESTS PASSED!"
